(setf family-data nil)

(defun addperson (x g p)
  (setf family-data (cons (list x p g) family-data)))
(addperson 'mark.peters 'm 'alice.peters)
(addperson 'tom.peters 'm 'david.peters)
(addperson 'alice.peters 'f 'jane.jones)
(addperson 'david.peters 'm nil)
(addperson 'mary.peters 'f 'david.smith)
(addperson 'john.jones 'm nil)
(addperson 'jane.jones 'f 'gary.jackson)
(addperson 'david.smith 'm nil)
(addperson 'susan.smith 'f nil)
(addperson 'gary.jackson 'm nil)
(addperson 'anna.jackson 'f nil)
(addperson 'jane.peters 'f 'alice.peters)
(addperson 'bob.peters 'm 'alice.peters)
(addperson 'jack.peters 'm 'david.peters)
(addperson 'steve.jones 'm 'jane.jones)
(addperson 'sally.jones 'f 'jane.jones)
(addperson 'tom.jones 'm 'steve.jones)
(addperson 'joyce.jones 'f nil)
(addperson 'tom.jackson 'm 'gary.jackson)
(addperson 'debbie.jackson 'f nil)
(addperson 'joan.jackson 'f 'tom.jackson)
(addperson 'bonnie.smith 'f 'tom.jackson)
(addperson 'alex.smith 'm nil)
(addperson 'bill.smith 'm 'bonnie.smith)
(addperson 'keith.smith 'm 'bill.smith)
(addperson 'julie.smith 'f 'keith.smith)
(addperson 'marla.adams 'f 'tom.jones)
