PROGRAM INTRODUCTION (OUTPUT);

{ERICK NAVE
 1-26-92 ICS
 INTRO.PAS IS A BRIEF PROGRAM MORE FOR GETTING USED TO PASCAL THAN ANYTHING.
     IT JUST SUPPLIES VITAL INFORMATION ABOUT MYSELF THROUGH THE USE OF
     CONSTANTS AND WRITELN.}

CONST
     NAME = 'ERICK NAVE.';
     MAJOR = 'COMPUTER SCIENCE.';
     RANK = 'FRESHMAN';
     HOME = 'CANTON.';
     AGE = '26.';

BEGIN
     WRITELN ('HELLO, I AM ',NAME);
     WRITELN ('MY MAJOR IS ',MAJOR);
     WRITELN ('I AM A ',RANK,' FROM ',HOME);
     WRITELN ('MY AGE IN THE YEAR 2000 WILL BE ',AGE);
END.

